services:
  reverse-proxy:
    image: traefik:v3.3
    depends_on:
      - back
      - play
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    restart: "$RESTART_POLICY"

  play:
    environment:
      DEBUG_MODE: "$DEBUG_MODE"
      JITSI_URL: "$JITSI_URL"
      JITSI_PRIVATE_MODE: "$JITSI_PRIVATE_MODE"
      ENABLE_MAP_EDITOR: "$ENABLE_MAP_EDITOR"
      MAP_EDITOR_ALLOWED_USERS: "$MAP_EDITOR_ALLOWED_USERS"
      TURN_SERVER: "$TURN_SERVER"
      TURN_USER: "$TURN_USER"
      TURN_PASSWORD: "$TURN_PASSWORD"
      TURN_STATIC_AUTH_SECRET: "$TURN_STATIC_AUTH_SECRET"
      STUN_SERVER: "$STUN_SERVER"
      SKIP_RENDER_OPTIMIZATIONS: "$SKIP_RENDER_OPTIMIZATIONS"
      MAX_PER_GROUP: "$MAX_PER_GROUP"
      MAX_USERNAME_LENGTH: "$MAX_USERNAME_LENGTH"
      DISABLE_ANONYMOUS: "$DISABLE_ANONYMOUS"
      DISABLE_NOTIFICATIONS: "$DISABLE_NOTIFICATIONS"
      SECRET_KEY: "$SECRET_KEY"
      API_URL: "back:50051"
      #Map editor
      INTERNAL_MAP_STORAGE_URL: "http://map-storage:3000"
      START_ROOM_URL: "$START_ROOM_URL"
      OPID_PROMPT: "$OPID_PROMPT"
      OPID_WOKA_NAME_POLICY: "$OPID_WOKA_NAME_POLICY"
      OPID_CLIENT_ID: "$OPID_CLIENT_ID"
      OPID_CLIENT_SECRET: "$OPID_CLIENT_SECRET"
      OPID_CLIENT_ISSUER: "$OPID_CLIENT_ISSUER"
      OPID_PROFILE_SCREEN_PROVIDER: "$OPID_PROFILE_SCREEN_PROVIDER"
      OPID_SCOPE: "$OPID_SCOPE"
      OPID_USERNAME_CLAIM: "$OPID_USERNAME_CLAIM"
      OPID_LOCALE_CLAIM: "$OPID_LOCALE_CLAIM"
      OPID_LOGOUT_REDIRECT_URL: "$OPID_LOGOUT_REDIRECT_URL"
      FALLBACK_LOCALE: "$FALLBACK_LOCALE"
      ENABLE_CHAT: "$ENABLE_CHAT"
      ENABLE_CHAT_UPLOAD: "$ENABLE_CHAT_UPLOAD"
      ENABLE_CHAT_ONLINE_LIST: "$ENABLE_CHAT_ONLINE_LIST"
      ENABLE_CHAT_DISCONNECTED_LIST: "$ENABLE_CHAT_DISCONNECTED_LIST"
      SERVER_NAME: "$SERVER_NAME"
      SERVER_MOTD: "$SERVER_MOTD"
      SERVER_ICON: "$SERVER_ICON"
      # Report issues menu
      ENABLE_REPORT_ISSUES_MENU: "$ENABLE_REPORT_ISSUES_MENU"
      REPORT_ISSUES_URL: "$REPORT_ISSUES_URL"
      ENABLE_OPENAPI_ENDPOINT: "true"
      ADMIN_API_TOKEN: "$ADMIN_API_TOKEN"
      ADMIN_API_URL: "$ADMIN_API_URL"
      ADMIN_URL: "$ADMIN_URL"
      ROOM_API_PORT: "50051"
      ROOM_API_SECRET_KEY: "$ROOM_API_SECRET_KEY"
      GRPC_VERBOSITY: "ERROR"
      GRPC_TRACE: "all"
      # LogRocket
      LOGROCKET_ID: "$LOGROCKET_ID"
      # Sentry integration
      SENTRY_ORG: "$SENTRY_ORG"
      SENTRY_PROJECT: "$SENTRY_PROJECT"
      SENTRY_DSN_FRONT: "$SENTRY_DSN_FRONT"
      SENTRY_DSN_PUSHER: "$SENTRY_DSN_PUSHER"
      SENTRY_ENVIRONMENT: "$SENTRY_ENVIRONMENT"
      SENTRY_RELEASE: "$SENTRY_RELEASE"
      SENTRY_TRACES_SAMPLE_RATE: "$SENTRY_TRACES_SAMPLE_RATE"
      # Room API
      JITSI_DOMAIN: "$JITSI_DOMAIN"
      JITSI_XMPP_DOMAIN: "$JITSI_XMPP_DOMAIN"
      JITSI_MUC_DOMAIN: "$JITSI_MUC_DOMAIN"
      WOKA_SPEED: "$WOKA_SPEED"
      FEATURE_FLAG_BROADCAST_AREAS: "$FEATURE_FLAG_BROADCAST_AREAS"
      # Tools integration
      KLAXOON_ENABLED: "$KLAXOON_ENABLED"
      KLAXOON_CLIENT_ID: "$KLAXOON_CLIENT_ID"
      YOUTUBE_ENABLED: "$YOUTUBE_ENABLED"
      GOOGLE_DRIVE_ENABLED: "$GOOGLE_DRIVE_ENABLED"
      GOOGLE_DOCS_ENABLED: "$GOOGLE_DOCS_ENABLED"
      GOOGLE_SHEETS_ENABLED: "$GOOGLE_SHEETS_ENABLED"
      GOOGLE_SLIDES_ENABLED: "$GOOGLE_SLIDES_ENABLED"
      ERASER_ENABLED: "$ERASER_ENABLED"
      EXCALIDRAW_ENABLED: "$EXCALIDRAW_ENABLED"
      EXCALIDRAW_DOMAINS: "$EXCALIDRAW_DOMAINS"
      EMBEDDED_DOMAINS_WHITELIST: "$EMBEDDED_DOMAINS_WHITELIST"
      CARDS_ENABLED: "$CARDS_ENABLED"
      # Report issues menu
      ACTIVE_REPORT_ISSUES_MENU: "true"
      URL_REPORT_ISSUES: "https://github.com/hackclub/the-pier/issues"
      PEER_VIDEO_LOW_BANDWIDTH: "$PEER_VIDEO_LOW_BANDWIDTH"
      PEER_VIDEO_RECOMMENDED_BANDWIDTH: "$PEER_VIDEO_RECOMMENDED_BANDWIDTH"
      PEER_SCREEN_SHARE_LOW_BANDWIDTH: "$PEER_SCREEN_SHARE_LOW_BANDWIDTH"
      PEER_SCREEN_SHARE_RECOMMENDED_BANDWIDTH: "$PEER_SCREEN_SHARE_RECOMMENDED_BANDWIDTH"
      # Google drive picker
      GOOGLE_DRIVE_PICKER_CLIENT_ID: "$GOOGLE_DRIVE_PICKER_CLIENT_ID"
      GOOGLE_DRIVE_PICKER_APP_ID: "$GOOGLE_DRIVE_PICKER_APP_ID"
      MAP_STORAGE_API_TOKEN: "${MAP_STORAGE_API_TOKEN:-${SECRET_KEY}}"
      #Chat
      MATRIX_API_URI: "$MATRIX_API_URI"
      MATRIX_PUBLIC_URI: "$MATRIX_PUBLIC_URI"
      MATRIX_ADMIN_USER: "$MATRIX_ADMIN_USER"
      MATRIX_ADMIN_PASSWORD: "$MATRIX_ADMIN_PASSWORD"
      MATRIX_DOMAIN: "$MATRIX_DOMAIN"
      # oEmbed providers
      EMBEDLY_KEY: "$EMBEDLY_KEY"
      IFRAMELY_KEY: "$IFRAMELY_KEY"
    restart: "$RESTART_POLICY"

  back:
    environment:
      ALLOW_ARTILLERY: "true"
      SECRET_JITSI_KEY: "$SECRET_JITSI_KEY"
      ENABLE_MAP_EDITOR: "$ENABLE_MAP_EDITOR"
      SECRET_KEY: "$SECRET_KEY"
      ADMIN_API_TOKEN: "$ADMIN_API_TOKEN"
      ADMIN_API_URL: "$ADMIN_API_URL"
      TURN_SERVER: "$TURN_SERVER"
      TURN_USER: "$TURN_USER"
      TURN_PASSWORD: "$TURN_PASSWORD"
      TURN_STATIC_AUTH_SECRET: "$TURN_STATIC_AUTH_SECRET"
      STUN_SERVER: "$STUN_SERVER"
      JITSI_URL: "$JITSI_URL"
      JITSI_ISS: "$JITSI_ISS"
      BBB_URL: "$BBB_URL"
      BBB_SECRET: "$BBB_SECRET"
      MAX_PER_GROUP: "$MAX_PER_GROUP"
      STORE_VARIABLES_FOR_LOCAL_MAPS: "$STORE_VARIABLES_FOR_LOCAL_MAPS"
      REDIS_HOST: "redis"
      PROMETHEUS_AUTHORIZATION_TOKEN: "$PROMETHEUS_AUTHORIZATION_TOKEN"
      MAP_STORAGE_URL: "map-storage:50053"
      INTERNAL_MAP_STORAGE_URL: "http://map-storage:3000"
      PLAYER_VARIABLES_MAX_TTL: "$PLAYER_VARIABLES_MAX_TTL"
      ENABLE_CHAT: "$ENABLE_CHAT"
      ENABLE_CHAT_UPLOAD: "$ENABLE_CHAT_UPLOAD"
      # Sentry integration
      SENTRY_DSN: "$SENTRY_DSN_BACK"
      SENTRY_ENVIRONMENT: "$SENTRY_ENVIRONMENT"
      SENTRY_RELEASE: "$SENTRY_RELEASE"
      SENTRY_TRACES_SAMPLE_RATE: "$SENTRY_TRACES_SAMPLE_RATE"
    restart: "$RESTART_POLICY"

  map-storage:
    environment:
      API_URL: back:50051
      PROMETHEUS_AUTHORIZATION_TOKEN: "$PROMETHEUS_AUTHORIZATION_TOKEN"
      AUTHENTICATION_STRATEGY: "$MAP_STORAGE_AUTHENTICATION_STRATEGY"
      ENABLE_BEARER_AUTHENTICATION: "$MAP_STORAGE_ENABLE_BEARER_AUTHENTICATION"
      ENABLE_BASIC_AUTHENTICATION: "$MAP_STORAGE_ENABLE_BASIC_AUTHENTICATION"
      ENABLE_DIGEST_AUTHENTICATION: "$MAP_STORAGE_ENABLE_DIGEST_AUTHENTICATION"
      AUTHENTICATION_USER: "$MAP_STORAGE_AUTHENTICATION_USER"
      AUTHENTICATION_PASSWORD: "$MAP_STORAGE_AUTHENTICATION_PASSWORD"
      AUTHENTICATION_TOKEN: "$MAP_STORAGE_AUTHENTICATION_TOKEN"
      AUTHENTICATION_VALIDATOR_URL: "$MAP_STORAGE_AUTHENTICATION_VALIDATOR_URL"
      # Sentry integration
      SENTRY_DSN: "$SENTRY_DSN_MAPSTORAGE"
      SENTRY_RELEASE: "$SENTRY_RELEASE"
      SENTRY_ENVIRONMENT: "$SENTRY_ENVIRONMENT"
      SENTRY_TRACES_SAMPLE_RATE: "$SENTRY_TRACES_SAMPLE_RATE"
      WHITELISTED_RESOURCE_URLS: ""
      MAP_STORAGE_API_TOKEN: "${MAP_STORAGE_API_TOKEN}"
    restart: "$RESTART_POLICY"

  uploader:
    environment:
      #AWS
      AWS_ACCESS_KEY_ID: "$AWS_ACCESS_KEY_ID"
      AWS_SECRET_ACCESS_KEY: "$AWS_SECRET_ACCESS_KEY"
      AWS_DEFAULT_REGION: "$AWS_DEFAULT_REGION"
      AWS_BUCKET: "$AWS_BUCKET"
      AWS_URL: "$AWS_URL"
      AWS_ENDPOINT: "$AWS_ENDPOINT"
      UPLOADER_AWS_SIGNED_URL_EXPIRATION: "$UPLOADER_AWS_SIGNED_URL_EXPIRATION"
      #REDIS
      REDIS_HOST: "$UPLOADER_REDIS_HOST"
      REDIS_PORT: "$UPLOADER_REDIS_PORT"
      REDIS_DB_NUMBER: "$UPLOADER_REDIS_DB_NUMBER"
      #CHAT
      ADMIN_API_URL: "$ADMIN_API_URL"
      ENABLE_CHAT_UPLOAD: "$ENABLE_CHAT_UPLOAD"
      UPLOAD_MAX_FILESIZE: "$UPLOAD_MAX_FILESIZE"
    restart: "$RESTART_POLICY"

  redis:
    image: redis:6
    restart: "$RESTART_POLICY"

  icon:
    image: matthiasluedtke/iconserver:v3.15.0
    restart: "$RESTART_POLICY"
